# Discrete distributions

include("discrete/benford.jl")
include("discrete/bernoulli.jl")
include("discrete/betabinomial.jl")
include("discrete/betapascal.jl")
include("discrete/binomial.jl")
include("discrete/discreteuniform.jl")
include("discrete/discreteweibull.jl")
include("discrete/gammapoisson.jl")
include("discrete/geometric.jl")
include("discrete/hypergeometric.jl")
include("discrete/logarithm.jl")
include("discrete/negativehypergeometric.jl")
include("discrete/pascal.jl")
include("discrete/poisson.jl")
include("discrete/polya.jl")
include("discrete/powerseries.jl")
include("discrete/rectangular.jl")
include("discrete/zeta.jl")
include("discrete/zipf.jl")
